import "./globals.css";
import Header from "../components/header";
import SideNav from "../components/side-nav";
import { ReduxProvider } from "../components/redux-provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <div className="flex flex-col w-screen h-screen bg-white">
            <Header />

            <div className="flex flex-grow overflow-hidden">
              <SideNav />
              <div className="flex h-full flex-grow items-center overflow-hidden">
                <div className="p-4 h-full flex flex-grow justify-center items-center overflow-auto">
                  {children}
                </div>
              </div>
            </div>
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
